### ISSUE TITLE
Log as optional dependency

### ISSUE THREAD

**Issue by alexwennerberg** [d2718/dumb-cgi#1]
Hi, I'm interested in this library. It'd be nice if `log` was an optional build dependency (ie, by gating all calls to `log` via feature flags). Would you be open to a PR where I make this change?

**Comment by d2718** [comment]
Sorry, this is the first time anyone has ever made a pull request for anything I've written, so I am only just know learning what the process looks like from this end. Please bear with me.

Anyway, I guess it should be clear that I already merged this (and also pushed it to crates.io, as version 0.7.0). Thanks for going to the trouble of sticking all those compiler directives in there.

**Comment by d2718** [comment]
Sorry, this is the first time anyone has ever made a pull request for anything I've written, so I am only just know learning what the process looks like from this end. Please bear with me.

Anyway, I guess it should be clear that I already merged this (and also pushed it to crates.io as version 0.7.0). Thanks for going to the trouble of sticking all those compiler directives in there.

**Comment by d2718** [comment]
Sorry, this is the first time anyone has ever made a pull request for anything I've written, so I am only just know learning what the process looks like from this end. Please bear with me.

Anyway, I guess it should be clear that I already merged this (and also pushed it to crates.io as version 0.7.0). Thanks for going to the trouble of sticking all those compiler directives in there.
